prompts = [
    "Write a short story about a time traveler who visits ancient Rome.",
    "Create a dialogue between two AI systems discussing human emotions.",
    "Describe a futuristic city in the year 2150.",
    "Write a letter from a mountain climber to their family back home.",
    "Create a fantasy world with unique magic systems and creatures.",
    "Explain quantum computing to a 10-year-old.",
    "Compare and contrast capitalism and socialism.",
    "Analyze the causes and effects of climate change.",
    "Explain the process of photosynthesis in detail.",
    "Break down the basics of blockchain technology.",
    "Suggest five innovative solutions to reduce plastic waste.",
    "Design a daily routine for maximum productivity.",
    "Create a meal plan for someone trying to eat more plant-based foods.",
    "Develop a strategy for a small business to improve online presence.",
    "Outline steps to learn a new language efficiently.",
    "Explain the significance of the French Revolution in modern history.",
    "Describe how the human immune system fights diseases.",
    "Outline the key principles of effective leadership.",
    "Explain the water cycle and its importance to Earth's ecosystems.",
    "Summarize the major theories of human consciousness.",
    "Invent a new sport that combines elements of basketball and chess.",
    "Design a sustainable house that uses minimal energy.",
    "Create a new recipe using only ingredients that begin with the letter 'C'.",
    "Develop a concept for a video game about interstellar diplomacy.",
    "Imagine a world where humans can photosynthesize and describe society.",
    "Describe a day in the life of an ancient Egyptian scribe.",
    "Compare cultural attitudes toward aging in three different societies.",
    "Explain how coffee changed global trade patterns.",
    "Analyze the impact of the printing press on European society.",
    "Describe the evolution of musical instruments across human history.",
    "Suggest techniques for managing anxiety in high-pressure situations.",
    "Create a guide for developing emotional intelligence.",
    "Outline a 30-day challenge to build a positive habit.",
    "Provide strategies for effective conflict resolution.",
    "Explain how to cultivate a growth mindset.",
    "Explain the principles behind machine learning algorithms.",
    "Describe how CRISPR gene editing technology works.",
    "Outline the process of designing a mobile application.",
    "Explain the scientific method and provide an example experiment.",
    "Compare different energy storage technologies.",
    "Discuss the ethical implications of genetic engineering in humans.",
    "Explore the concept of justice across different philosophical traditions.",
    "Analyze the trolley problem from multiple ethical perspectives.",
    "Consider the relationship between technology and human happiness.",
    "Examine the philosophical question of whether free will exists.",
    "Create a comprehensive guide to starting urban gardening.",
    "Develop a training program for a first-time marathon runner.",
    "Write a speech about the importance of arts education.",
    "Design a workshop on effective cross-cultural communication.",
    "Create a beginner's guide to understanding classical music."
]